"""Seed 55+ global insurtech news sources into the database."""
import asyncio
from slugify import slugify
from app.database import AsyncSessionLocal
from app.models.source import Source
from sqlalchemy import select

SOURCES = [
    # ── InsurTech Specialized ──────────────────────────────────────────────────
    {
        "name": "InsurTech Magazine",
        "url": "https://www.insurtechmagazine.com",
        "rss_url": "https://www.insurtechmagazine.com/rss",
        "source_type": "rss",
        "region": "global",
        "category": "trade",
        "quality_score": 0.92,
        "description": "Leading global insurtech publication covering innovation, technology, and transformation.",
    },
    {
        "name": "Coverager",
        "url": "https://coverager.com",
        "rss_url": "https://coverager.com/feed/",
        "source_type": "rss",
        "region": "US",
        "category": "trade",
        "quality_score": 0.95,
        "description": "Daily insurtech intelligence — product news, funding, strategy.",
    },
    {
        "name": "Insurance Thought Leadership",
        "url": "https://insurancethoughtleadership.com",
        "rss_url": "https://insurancethoughtleadership.com/feed/",
        "source_type": "rss",
        "region": "US",
        "category": "trade",
        "quality_score": 0.88,
        "description": "Long-form analysis and opinion from insurance executives and innovators.",
    },
    {
        "name": "Digital Insurance",
        "url": "https://www.dig-in.com",
        "rss_url": "https://www.dig-in.com/rss/news",
        "source_type": "rss",
        "region": "US",
        "category": "trade",
        "quality_score": 0.90,
        "description": "Digital Insurance covers the intersection of technology and insurance.",
    },
    {
        "name": "InsurTech Insights",
        "url": "https://insurtechinsights.com",
        "rss_url": "https://insurtechinsights.com/feed/",
        "source_type": "rss",
        "region": "EU",
        "category": "trade",
        "quality_score": 0.85,
        "description": "European insurtech events, news and community.",
    },
    {
        "name": "The Insurer",
        "url": "https://www.theinsurer.com",
        "rss_url": "https://www.theinsurer.com/feed/",
        "source_type": "rss",
        "region": "global",
        "category": "trade",
        "quality_score": 0.88,
        "description": "Breaking news for the global insurance market.",
    },
    {
        "name": "Insurance Journal",
        "url": "https://www.insurancejournal.com",
        "rss_url": "https://www.insurancejournal.com/rss/news/",
        "source_type": "rss",
        "region": "US",
        "category": "trade",
        "quality_score": 0.87,
        "description": "P&C insurance news for agents and brokers in the US.",
    },
    {
        "name": "PropertyCasualty360",
        "url": "https://www.propertycasualty360.com",
        "rss_url": "https://www.propertycasualty360.com/rss/",
        "source_type": "rss",
        "region": "US",
        "category": "trade",
        "quality_score": 0.83,
        "description": "Property and casualty insurance professionals' resource.",
    },
    {
        "name": "Reinsurance News",
        "url": "https://www.reinsurancene.ws",
        "rss_url": "https://www.reinsurancene.ws/feed/",
        "source_type": "rss",
        "region": "global",
        "category": "trade",
        "quality_score": 0.86,
        "description": "Global reinsurance and ILS news.",
    },
    {
        "name": "Artemis",
        "url": "https://www.artemis.bm",
        "rss_url": "https://www.artemis.bm/feed/",
        "source_type": "rss",
        "region": "global",
        "category": "trade",
        "quality_score": 0.89,
        "description": "ILS, catastrophe bonds, insurance-linked securities news.",
    },
    {
        "name": "Insurance Age",
        "url": "https://www.insuranceage.co.uk",
        "rss_url": "https://www.insuranceage.co.uk/rss.xml",
        "source_type": "rss",
        "region": "EU",
        "category": "trade",
        "quality_score": 0.82,
        "description": "UK personal lines and commercial insurance news.",
    },
    {
        "name": "Post Online",
        "url": "https://www.postonline.co.uk",
        "rss_url": "https://www.postonline.co.uk/rss.xml",
        "source_type": "rss",
        "region": "EU",
        "category": "trade",
        "quality_score": 0.81,
        "description": "UK insurance market news and analysis.",
    },
    {
        "name": "Insurance Business",
        "url": "https://www.insurancebusinessmag.com",
        "rss_url": "https://www.insurancebusinessmag.com/rss/all-news",
        "source_type": "rss",
        "region": "global",
        "category": "trade",
        "quality_score": 0.84,
        "description": "Global insurance business news and strategy.",
    },
    {
        "name": "Global Insurance Forum",
        "url": "https://www.globalinsuranceforum.com",
        "rss_url": None,
        "source_type": "scrape",
        "region": "global",
        "category": "trade",
        "quality_score": 0.78,
        "description": "Global insurance industry forum news and events.",
    },
    # ── Fintech / VC / Startup Press ──────────────────────────────────────────
    {
        "name": "TechCrunch Insurance",
        "url": "https://techcrunch.com/tag/insurance/",
        "rss_url": "https://techcrunch.com/tag/insurance/feed/",
        "source_type": "rss",
        "region": "US",
        "category": "vc",
        "quality_score": 0.90,
        "description": "TechCrunch coverage of insurance startups and funding.",
    },
    {
        "name": "Crunchbase News",
        "url": "https://news.crunchbase.com",
        "rss_url": "https://news.crunchbase.com/feed/",
        "source_type": "rss",
        "region": "US",
        "category": "vc",
        "quality_score": 0.88,
        "description": "Startup funding and venture capital news.",
    },
    {
        "name": "Fintech Futures",
        "url": "https://www.fintechfutures.com",
        "rss_url": "https://www.fintechfutures.com/feed/",
        "source_type": "rss",
        "region": "global",
        "category": "fintech",
        "quality_score": 0.85,
        "description": "Fintech and insurtech breaking news.",
    },
    {
        "name": "PYMNTS Insurance",
        "url": "https://www.pymnts.com/category/insurance/",
        "rss_url": "https://www.pymnts.com/category/insurance/feed/",
        "source_type": "rss",
        "region": "US",
        "category": "fintech",
        "quality_score": 0.82,
        "description": "Insurance payments and fintech news from PYMNTS.",
    },
    {
        "name": "Fintech Magazine",
        "url": "https://fintechmagazine.com",
        "rss_url": "https://fintechmagazine.com/rss",
        "source_type": "rss",
        "region": "global",
        "category": "fintech",
        "quality_score": 0.80,
        "description": "Fintech Magazine covering insurance, banking, and payments.",
    },
    {
        "name": "The Block",
        "url": "https://www.theblock.co",
        "rss_url": "https://www.theblock.co/rss.xml",
        "source_type": "rss",
        "region": "global",
        "category": "fintech",
        "quality_score": 0.79,
        "description": "Blockchain and DeFi including parametric insurance.",
    },
    {
        "name": "Reuters Finance",
        "url": "https://www.reuters.com/finance/",
        "rss_url": "https://feeds.reuters.com/reuters/financialsNews",
        "source_type": "rss",
        "region": "global",
        "category": "press",
        "quality_score": 0.93,
        "description": "Reuters financial news including insurance.",
    },
    {
        "name": "Bloomberg Insurance",
        "url": "https://www.bloomberg.com/insurance",
        "rss_url": None,
        "source_type": "scrape",
        "region": "global",
        "category": "press",
        "quality_score": 0.95,
        "description": "Bloomberg coverage of the insurance industry.",
    },
    {
        "name": "Financial Times Insurance",
        "url": "https://www.ft.com/insurance",
        "rss_url": None,
        "source_type": "scrape",
        "region": "global",
        "category": "press",
        "quality_score": 0.94,
        "description": "FT insurance sector coverage.",
    },
    {
        "name": "Business Insurance",
        "url": "https://www.businessinsurance.com",
        "rss_url": "https://www.businessinsurance.com/rss/news.xml",
        "source_type": "rss",
        "region": "US",
        "category": "trade",
        "quality_score": 0.86,
        "description": "Commercial insurance and risk management news.",
    },
    # ── Regulatory Bodies ──────────────────────────────────────────────────────
    {
        "name": "EIOPA",
        "url": "https://www.eiopa.europa.eu",
        "rss_url": "https://www.eiopa.europa.eu/media/news_en.rss",
        "source_type": "rss",
        "region": "EU",
        "category": "regulatory",
        "quality_score": 0.95,
        "description": "European Insurance and Occupational Pensions Authority official news.",
    },
    {
        "name": "FCA News",
        "url": "https://www.fca.org.uk/news",
        "rss_url": "https://www.fca.org.uk/news/rss.xml",
        "source_type": "rss",
        "region": "EU",
        "category": "regulatory",
        "quality_score": 0.95,
        "description": "UK Financial Conduct Authority regulatory updates.",
    },
    {
        "name": "NAIC",
        "url": "https://content.naic.org/article",
        "rss_url": None,
        "source_type": "scrape",
        "region": "US",
        "category": "regulatory",
        "quality_score": 0.92,
        "description": "US National Association of Insurance Commissioners.",
    },
    {
        "name": "FSB",
        "url": "https://www.fsb.org",
        "rss_url": "https://www.fsb.org/feed/",
        "source_type": "rss",
        "region": "global",
        "category": "regulatory",
        "quality_score": 0.90,
        "description": "Financial Stability Board news and reports.",
    },
    {
        "name": "PRA News",
        "url": "https://www.bankofengland.co.uk/prudential-regulation",
        "rss_url": "https://www.bankofengland.co.uk/rss/news",
        "source_type": "rss",
        "region": "EU",
        "category": "regulatory",
        "quality_score": 0.89,
        "description": "Bank of England Prudential Regulation Authority.",
    },
    {
        "name": "IAIS",
        "url": "https://www.iaisweb.org",
        "rss_url": None,
        "source_type": "scrape",
        "region": "global",
        "category": "regulatory",
        "quality_score": 0.88,
        "description": "International Association of Insurance Supervisors.",
    },
    # ── Research & Analysts ────────────────────────────────────────────────────
    {
        "name": "Swiss Re Institute",
        "url": "https://www.swissre.com/institute",
        "rss_url": "https://www.swissre.com/institute/research/rss.xml",
        "source_type": "rss",
        "region": "global",
        "category": "research",
        "quality_score": 0.95,
        "description": "Swiss Re Institute sigma reports and insurance research.",
    },
    {
        "name": "Munich Re Research",
        "url": "https://www.munichre.com/en/risks/research.html",
        "rss_url": None,
        "source_type": "scrape",
        "region": "global",
        "category": "research",
        "quality_score": 0.93,
        "description": "Munich Re global insurance research and NatCat analysis.",
    },
    {
        "name": "Lloyd's of London",
        "url": "https://www.lloyds.com/news-and-insights",
        "rss_url": "https://www.lloyds.com/rss/news",
        "source_type": "rss",
        "region": "EU",
        "category": "research",
        "quality_score": 0.91,
        "description": "Lloyd's market news, reports and innovation.",
    },
    {
        "name": "Deloitte Insurance",
        "url": "https://www2.deloitte.com/us/en/pages/financial-services/topics/insurance.html",
        "rss_url": None,
        "source_type": "scrape",
        "region": "global",
        "category": "research",
        "quality_score": 0.88,
        "description": "Deloitte insurance industry insights and reports.",
    },
    {
        "name": "McKinsey Insurance",
        "url": "https://www.mckinsey.com/industries/financial-services/our-insights/insurance",
        "rss_url": None,
        "source_type": "scrape",
        "region": "global",
        "category": "research",
        "quality_score": 0.92,
        "description": "McKinsey insurance insights and strategy.",
    },
    {
        "name": "Accenture Insurance",
        "url": "https://www.accenture.com/us-en/insights/insurance-index",
        "rss_url": None,
        "source_type": "scrape",
        "region": "global",
        "category": "research",
        "quality_score": 0.86,
        "description": "Accenture insurance technology and innovation research.",
    },
    {
        "name": "EY Insurance",
        "url": "https://www.ey.com/en_gl/insurance",
        "rss_url": None,
        "source_type": "scrape",
        "region": "global",
        "category": "research",
        "quality_score": 0.85,
        "description": "EY insurance sector perspectives.",
    },
    # ── APAC ──────────────────────────────────────────────────────────────────
    {
        "name": "Fintech News Singapore (InsurTech)",
        "url": "https://fintechnews.sg/category/insurtech/",
        "rss_url": "https://fintechnews.sg/category/insurtech/feed/",
        "source_type": "rss",
        "region": "APAC",
        "category": "trade",
        "quality_score": 0.82,
        "description": "Singapore insurtech and fintech news.",
    },
    {
        "name": "Fintech News Hong Kong",
        "url": "https://fintechnews.hk",
        "rss_url": "https://fintechnews.hk/feed/",
        "source_type": "rss",
        "region": "APAC",
        "category": "trade",
        "quality_score": 0.80,
        "description": "Hong Kong and Greater China fintech/insurtech news.",
    },
    {
        "name": "Insurance Asia News",
        "url": "https://insuranceasianews.com",
        "rss_url": "https://insuranceasianews.com/feed/",
        "source_type": "rss",
        "region": "APAC",
        "category": "trade",
        "quality_score": 0.83,
        "description": "Pan-Asian insurance market news and analysis.",
    },
    {
        "name": "Asia Insurance Review",
        "url": "https://www.asiainsurancereview.com",
        "rss_url": None,
        "source_type": "scrape",
        "region": "APAC",
        "category": "trade",
        "quality_score": 0.84,
        "description": "Asia insurance industry publication.",
    },
    {
        "name": "Fintech News India",
        "url": "https://inc42.com/tag/insurtech/",
        "rss_url": "https://inc42.com/tag/insurtech/feed/",
        "source_type": "rss",
        "region": "APAC",
        "category": "trade",
        "quality_score": 0.79,
        "description": "India insurtech startup news from Inc42.",
    },
    # ── Europe ────────────────────────────────────────────────────────────────
    {
        "name": "InsurTech Hub Munich",
        "url": "https://www.insurtechhub.com",
        "rss_url": "https://www.insurtechhub.com/feed/",
        "source_type": "rss",
        "region": "EU",
        "category": "trade",
        "quality_score": 0.81,
        "description": "Munich insurtech hub news and community.",
    },
    {
        "name": "InsTech London",
        "url": "https://www.instech.london",
        "rss_url": "https://www.instech.london/news?format=rss",
        "source_type": "rss",
        "region": "EU",
        "category": "trade",
        "quality_score": 0.87,
        "description": "London insurtech ecosystem news and events.",
    },
    {
        "name": "Sifted Insurance",
        "url": "https://sifted.eu/sector/fintech",
        "rss_url": "https://sifted.eu/rss",
        "source_type": "rss",
        "region": "EU",
        "category": "vc",
        "quality_score": 0.83,
        "description": "European startup and scale-up news.",
    },
    # ── LATAM ────────────────────────────────────────────────────────────────
    {
        "name": "Latam Fintech Hub",
        "url": "https://www.latamfintechhub.com",
        "rss_url": None,
        "source_type": "scrape",
        "region": "LATAM",
        "category": "trade",
        "quality_score": 0.78,
        "description": "Latin America fintech and insurtech ecosystem.",
    },
    {
        "name": "Finnovista",
        "url": "https://www.finnovista.com/en/news/",
        "rss_url": "https://www.finnovista.com/feed/",
        "source_type": "rss",
        "region": "LATAM",
        "category": "vc",
        "quality_score": 0.80,
        "description": "Fintech and insurtech innovation in Latin America.",
    },
    # ── MEA ──────────────────────────────────────────────────────────────────
    {
        "name": "Middle East Insurance Review",
        "url": "https://www.meinsurancereview.com",
        "rss_url": None,
        "source_type": "scrape",
        "region": "MEA",
        "category": "trade",
        "quality_score": 0.79,
        "description": "Middle East and Africa insurance market news.",
    },
    {
        "name": "Fintech Africa",
        "url": "https://fintechafrica.net",
        "rss_url": "https://fintechafrica.net/feed/",
        "source_type": "rss",
        "region": "MEA",
        "category": "trade",
        "quality_score": 0.77,
        "description": "African fintech and insurance innovation.",
    },
    # ── AI / Tech / Cyber ─────────────────────────────────────────────────────
    {
        "name": "Dark Reading (Cyber Insurance)",
        "url": "https://www.darkreading.com",
        "rss_url": "https://www.darkreading.com/rss.xml",
        "source_type": "rss",
        "region": "US",
        "category": "tech",
        "quality_score": 0.84,
        "description": "Cybersecurity news relevant to cyber insurance.",
    },
    {
        "name": "Carrier Management",
        "url": "https://www.carriermanagement.com",
        "rss_url": "https://www.carriermanagement.com/rss/",
        "source_type": "rss",
        "region": "US",
        "category": "trade",
        "quality_score": 0.83,
        "description": "P&C carrier strategy and technology news.",
    },
    {
        "name": "Claims Journal",
        "url": "https://www.claimsjournal.com",
        "rss_url": "https://www.claimsjournal.com/rss/",
        "source_type": "rss",
        "region": "US",
        "category": "trade",
        "quality_score": 0.81,
        "description": "Claims management and technology news.",
    },
    {
        "name": "Insurance Innovation Reporter",
        "url": "https://iireporter.com",
        "rss_url": "https://iireporter.com/feed/",
        "source_type": "rss",
        "region": "US",
        "category": "trade",
        "quality_score": 0.84,
        "description": "Insurance technology innovation news and analysis.",
    },
    {
        "name": "Embedded Insurance News",
        "url": "https://embedded-insurance.news",
        "rss_url": "https://embedded-insurance.news/feed/",
        "source_type": "rss",
        "region": "global",
        "category": "trade",
        "quality_score": 0.86,
        "description": "Dedicated embedded insurance news and analysis.",
    },
    {
        "name": "Parametric Insurance Review",
        "url": "https://www.parametricinsurancereview.com",
        "rss_url": "https://www.parametricinsurancereview.com/feed/",
        "source_type": "rss",
        "region": "global",
        "category": "trade",
        "quality_score": 0.85,
        "description": "Parametric and index-based insurance news.",
    },
]


async def seed():
    async with AsyncSessionLocal() as db:
        existing = await db.execute(select(Source))
        existing_slugs = {s.slug for s in existing.scalars().all()}

        added = 0
        for s in SOURCES:
            slug = slugify(s["name"])
            if slug in existing_slugs:
                continue
            source = Source(slug=slug, **s)
            db.add(source)
            added += 1

        await db.commit()
        print(f"Seeded {added} sources ({len(SOURCES) - added} already existed)")


if __name__ == "__main__":
    asyncio.run(seed())
